site_name: Micro Simulations for Education
site_description: 'Resources for teaching classes on Micro Simulators using generative AI and ChatGPT.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/microsims'
repo_url: 'https://github.com/dmccreary/microsims'

nav:
  - Home: index.md
  - About: about.md
  - References: references.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - Creative Commons License: license.md
  - Contact: contact.md

# Dan's MicroSite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  # logo: img/logo.png
  # favicon: img/favicon.ico
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-BBR7MPK96Z